import type { Model } from "@opencode-ai/sdk/v2"

// ── api.npm source constant ────────────────────────────────────────────
// Default: npm package name (used when package is published).
// Local dev override: set WINDSURF_AUTH_LOCAL=1 to use the local dist path
// (e.g. `export WINDSURF_AUTH_LOCAL=1` before running opencode dev build).
const PROVIDER_NPM = (): string => {
  if (typeof process !== "undefined" && process.env["WINDSURF_AUTH_LOCAL"] === "1") {
    return "file:///Users/nghiango-mbp/opencode-learn/opencode-windsurf-auth/dist/index.js"
  }
  return "@ngotrnghia1811/opencode-windsurf-auth"
}

const BASE_MODEL: Omit<Model, "id" | "name" | "api"> = {
  providerID: "windsurf-devin-provider",
  family: "cascade",
  capabilities: {
    temperature: false,
    reasoning: false,
    attachment: false,
    toolcall: true,
    input: { text: true, audio: false, image: false, video: false, pdf: false },
    output: { text: true, audio: false, image: false, video: false, pdf: false },
    interleaved: false,
  },
  cost: {
    input: 0,
    output: 0,
    cache: { read: 0, write: 0 },
  },
  limit: {
    context: 128_000,
    output: 8_192,
  },
  status: "active",
  options: {},
  headers: {},
  release_date: "2024-01-01",
}

const windsurfModel = (
  key: string,
  name: string,
  apiId: string,
  inputCost: number,
  outputCost: number,
  reasoning = false,
): Model => ({
  ...BASE_MODEL,
  id: `windsurf/${key}`,
  name: `ws ${name}`,
  capabilities: { ...BASE_MODEL.capabilities, reasoning },
  cost: { input: inputCost, output: outputCost, cache: { read: 0, write: 0 } },
  api: { id: apiId, url: "", npm: PROVIDER_NPM() },
})

export const WINDSURF_MODELS: Record<string, Model> = {
  // ── Windsurf native models ──────────────────────────────────────────────
  adaptive: windsurfModel("adaptive", "Adaptive", "adaptive", 0.5, 2),
  "arena-fast": windsurfModel("arena-fast", "Fast Arena", "arena-fast", 0.1, 0.5),
  "arena-mixed": windsurfModel("arena-mixed", "Hybrid Arena", "arena-mixed", 1, 5),
  "arena-smart": windsurfModel("arena-smart", "Frontier Arena", "arena-smart", 3, 15),

  // ── Anthropic ───────────────────────────────────────────────────────────
  "claude-opus-4-1": windsurfModel(
    "claude-opus-4-1",
    "Claude Opus 4.1",
    "MODEL_CLAUDE_4_1_OPUS",
    5,
    25,
  ),
  "claude-opus-4-1-thinking": windsurfModel(
    "claude-opus-4-1-thinking",
    "Claude Opus 4.1 Thinking",
    "MODEL_CLAUDE_4_1_OPUS_THINKING",
    5,
    25,
    true,
  ),
  "claude-opus-4-5": windsurfModel(
    "claude-opus-4-5",
    "Claude Opus 4.5",
    "MODEL_CLAUDE_4_5_OPUS",
    5,
    25,
  ),
  "claude-opus-4-5-thinking": windsurfModel(
    "claude-opus-4-5-thinking",
    "Claude Opus 4.5 Thinking",
    "MODEL_CLAUDE_4_5_OPUS_THINKING",
    5,
    25,
    true,
  ),
  "claude-opus-4-6": windsurfModel(
    "claude-opus-4-6",
    "Claude Opus 4.6",
    "claude-opus-4-6",
    5,
    25,
  ),
  "claude-opus-4-6-1m": windsurfModel(
    "claude-opus-4-6-1m",
    "Claude Opus 4.6 1M",
    "claude-opus-4-6-1m",
    5,
    25,
  ),
  "claude-opus-4-6-fast": windsurfModel(
    "claude-opus-4-6-fast",
    "Claude Opus 4.6 Fast",
    "claude-opus-4-6-fast",
    30,
    150,
  ),
  "claude-opus-4-6-thinking": windsurfModel(
    "claude-opus-4-6-thinking",
    "Claude Opus 4.6 Thinking",
    "claude-opus-4-6-thinking",
    5,
    25,
    true,
  ),
  "claude-opus-4-6-thinking-1m": windsurfModel(
    "claude-opus-4-6-thinking-1m",
    "Claude Opus 4.6 Thinking 1M",
    "claude-opus-4-6-thinking-1m",
    5,
    25,
    true,
  ),
  "claude-opus-4-6-thinking-fast": windsurfModel(
    "claude-opus-4-6-thinking-fast",
    "Claude Opus 4.6 Thinking Fast",
    "claude-opus-4-6-thinking-fast",
    30,
    150,
    true,
  ),
  "claude-opus-4-7-high": windsurfModel(
    "claude-opus-4-7-high",
    "Claude Opus 4.7 High",
    "claude-opus-4-7-high",
    5,
    25,
  ),
  "claude-opus-4-7-high-fast": windsurfModel(
    "claude-opus-4-7-high-fast",
    "Claude Opus 4.7 High Fast",
    "claude-opus-4-7-high-fast",
    30,
    150,
  ),
  "claude-opus-4-7-low": windsurfModel(
    "claude-opus-4-7-low",
    "Claude Opus 4.7 Low",
    "claude-opus-4-7-low",
    5,
    25,
  ),
  "claude-opus-4-7-low-fast": windsurfModel(
    "claude-opus-4-7-low-fast",
    "Claude Opus 4.7 Low Fast",
    "claude-opus-4-7-low-fast",
    30,
    150,
  ),
  "claude-opus-4-7-max": windsurfModel(
    "claude-opus-4-7-max",
    "Claude Opus 4.7 Max",
    "claude-opus-4-7-max",
    5,
    25,
  ),
  "claude-opus-4-7-max-fast": windsurfModel(
    "claude-opus-4-7-max-fast",
    "Claude Opus 4.7 Max Fast",
    "claude-opus-4-7-max-fast",
    30,
    150,
  ),
  "claude-opus-4-7-medium": windsurfModel(
    "claude-opus-4-7-medium",
    "Claude Opus 4.7 Medium",
    "claude-opus-4-7-medium",
    5,
    25,
  ),
  "claude-opus-4-7-medium-fast": windsurfModel(
    "claude-opus-4-7-medium-fast",
    "Claude Opus 4.7 Medium Fast",
    "claude-opus-4-7-medium-fast",
    30,
    150,
  ),
  "claude-opus-4-7-xhigh": windsurfModel(
    "claude-opus-4-7-xhigh",
    "Claude Opus 4.7 XHigh",
    "claude-opus-4-7-xhigh",
    5,
    25,
  ),
  "claude-opus-4-7-xhigh-fast": windsurfModel(
    "claude-opus-4-7-xhigh-fast",
    "Claude Opus 4.7 XHigh Fast",
    "claude-opus-4-7-xhigh-fast",
    30,
    150,
  ),
  "claude-opus-4-8-high": windsurfModel(
    "claude-opus-4-8-high",
    "Claude Opus 4.8 High",
    "claude-opus-4-8-high",
    5,
    25,
  ),
  "claude-opus-4-8-high-fast": windsurfModel(
    "claude-opus-4-8-high-fast",
    "Claude Opus 4.8 High Fast",
    "claude-opus-4-8-high-fast",
    10,
    50,
  ),
  "claude-opus-4-8-low": windsurfModel(
    "claude-opus-4-8-low",
    "Claude Opus 4.8 Low",
    "claude-opus-4-8-low",
    5,
    25,
  ),
  "claude-opus-4-8-low-fast": windsurfModel(
    "claude-opus-4-8-low-fast",
    "Claude Opus 4.8 Low Fast",
    "claude-opus-4-8-low-fast",
    10,
    50,
  ),
  "claude-opus-4-8-max": windsurfModel(
    "claude-opus-4-8-max",
    "Claude Opus 4.8 Max",
    "claude-opus-4-8-max",
    5,
    25,
  ),
  "claude-opus-4-8-max-fast": windsurfModel(
    "claude-opus-4-8-max-fast",
    "Claude Opus 4.8 Max Fast",
    "claude-opus-4-8-max-fast",
    10,
    50,
  ),
  "claude-opus-4-8-medium": windsurfModel(
    "claude-opus-4-8-medium",
    "Claude Opus 4.8 Medium",
    "claude-opus-4-8-medium",
    5,
    25,
  ),
  "claude-opus-4-8-medium-fast": windsurfModel(
    "claude-opus-4-8-medium-fast",
    "Claude Opus 4.8 Medium Fast",
    "claude-opus-4-8-medium-fast",
    10,
    50,
  ),
  "claude-opus-4-8-xhigh": windsurfModel(
    "claude-opus-4-8-xhigh",
    "Claude Opus 4.8 XHigh",
    "claude-opus-4-8-xhigh",
    5,
    25,
  ),
  "claude-opus-4-8-xhigh-fast": windsurfModel(
    "claude-opus-4-8-xhigh-fast",
    "Claude Opus 4.8 XHigh Fast",
    "claude-opus-4-8-xhigh-fast",
    10,
    50,
  ),
  "claude-sonnet-4": windsurfModel(
    "claude-sonnet-4",
    "Claude Sonnet 4",
    "MODEL_CLAUDE_4_SONNET",
    3,
    15,
  ),
  "claude-sonnet-4-thinking": windsurfModel(
    "claude-sonnet-4-thinking",
    "Claude Sonnet 4 Thinking",
    "MODEL_CLAUDE_4_SONNET_THINKING",
    3,
    15,
    true,
  ),
  "claude-sonnet-4-5": windsurfModel(
    "claude-sonnet-4-5",
    "Claude Sonnet 4.5",
    "MODEL_PRIVATE_2",
    3,
    15,
  ),
  "claude-sonnet-4-5-thinking": windsurfModel(
    "claude-sonnet-4-5-thinking",
    "Claude Sonnet 4.5 Thinking",
    "MODEL_PRIVATE_3",
    3,
    15,
    true,
  ),
  "claude-sonnet-4-6": windsurfModel(
    "claude-sonnet-4-6",
    "Claude Sonnet 4.6",
    "claude-sonnet-4-6",
    3,
    15,
  ),
  "claude-sonnet-4-6-1m": windsurfModel(
    "claude-sonnet-4-6-1m",
    "Claude Sonnet 4.6 1M",
    "claude-sonnet-4-6-1m",
    3,
    15,
  ),
  "claude-sonnet-4-6-thinking": windsurfModel(
    "claude-sonnet-4-6-thinking",
    "Claude Sonnet 4.6 Thinking",
    "claude-sonnet-4-6-thinking",
    3,
    15,
    true,
  ),
  "claude-sonnet-4-6-thinking-1m": windsurfModel(
    "claude-sonnet-4-6-thinking-1m",
    "Claude Sonnet 4.6 Thinking 1M",
    "claude-sonnet-4-6-thinking-1m",
    3,
    15,
    true,
  ),
  "claude-haiku-4-5": windsurfModel(
    "claude-haiku-4-5",
    "Claude Haiku 4.5",
    "MODEL_PRIVATE_11",
    1,
    5,
  ),
  "opus-4-7-review": windsurfModel(
    "opus-4-7-review",
    "Opus 4.7 Review",
    "opus-4-7-review",
    5,
    25,
  ),

  // ── OpenAI ──────────────────────────────────────────────────────────────
  "gpt-4o": windsurfModel(
    "gpt-4o",
    "GPT-4o",
    "MODEL_CHAT_GPT_4O_2024_08_06",
    2.5,
    10,
  ),
  "gpt-4-1": windsurfModel(
    "gpt-4-1",
    "GPT-4.1",
    "MODEL_CHAT_GPT_4_1_2025_04_14",
    2,
    8,
  ),
  o3: windsurfModel("o3", "o3", "MODEL_CHAT_O3", 2, 8),
  "o3-high": windsurfModel("o3-high", "o3 High Reasoning", "MODEL_CHAT_O3_HIGH", 2, 8),
  "gpt-5-codex": windsurfModel(
    "gpt-5-codex",
    "GPT-5-Codex",
    "MODEL_CHAT_GPT_5_CODEX",
    1.25,
    10,
  ),
  "gpt-5-codex-private": windsurfModel(
    "gpt-5-codex-private",
    "GPT-5-Codex",
    "MODEL_PRIVATE_5",
    1.25,
    10,
  ),
  "gpt-5-low": windsurfModel(
    "gpt-5-low",
    "GPT-5 Low Thinking",
    "MODEL_PRIVATE_6",
    1.25,
    10,
  ),
  "gpt-5-medium": windsurfModel(
    "gpt-5-medium",
    "GPT-5 Medium Thinking",
    "MODEL_PRIVATE_7",
    1.25,
    10,
  ),
  "gpt-5-high": windsurfModel(
    "gpt-5-high",
    "GPT-5 High Thinking",
    "MODEL_PRIVATE_8",
    1.25,
    10,
  ),

  // ── GPT-5.1 ─────────────────────────────────────────────────────────────
  "gpt-5-1-none": windsurfModel(
    "gpt-5-1-none",
    "GPT-5.1 No Thinking",
    "MODEL_PRIVATE_12",
    1.25,
    10,
  ),
  "gpt-5-1-low": windsurfModel(
    "gpt-5-1-low",
    "GPT-5.1 Low Thinking",
    "MODEL_PRIVATE_13",
    1.25,
    10,
  ),
  "gpt-5-1-medium": windsurfModel(
    "gpt-5-1-medium",
    "GPT-5.1 Medium Thinking",
    "MODEL_PRIVATE_14",
    1.25,
    10,
  ),
  "gpt-5-1-high": windsurfModel(
    "gpt-5-1-high",
    "GPT-5.1 High Thinking",
    "MODEL_PRIVATE_15",
    1.25,
    10,
  ),
  "gpt-5-1-none-fast": windsurfModel(
    "gpt-5-1-none-fast",
    "GPT-5.1 No Thinking Fast",
    "MODEL_PRIVATE_20",
    2.5,
    20,
  ),
  "gpt-5-1-low-fast": windsurfModel(
    "gpt-5-1-low-fast",
    "GPT-5.1 Low Thinking Fast",
    "MODEL_PRIVATE_21",
    2.5,
    20,
  ),
  "gpt-5-1-medium-fast": windsurfModel(
    "gpt-5-1-medium-fast",
    "GPT-5.1 Medium Thinking Fast",
    "MODEL_PRIVATE_22",
    2.5,
    20,
  ),
  "gpt-5-1-high-fast": windsurfModel(
    "gpt-5-1-high-fast",
    "GPT-5.1 High Thinking Fast",
    "MODEL_PRIVATE_23",
    2.5,
    20,
  ),

  // ── GPT-5.1 Codex ───────────────────────────────────────────────────────
  "gpt-5-1-codex-low": windsurfModel(
    "gpt-5-1-codex-low",
    "GPT-5.1-Codex Low",
    "MODEL_GPT_5_1_CODEX_LOW",
    1.25,
    10,
  ),
  "gpt-5-1-codex-max-high": windsurfModel(
    "gpt-5-1-codex-max-high",
    "GPT-5.1-Codex Max High",
    "MODEL_GPT_5_1_CODEX_MAX_HIGH",
    1.25,
    10,
  ),
  "gpt-5-1-codex-max-low": windsurfModel(
    "gpt-5-1-codex-max-low",
    "GPT-5.1-Codex Max Low",
    "MODEL_GPT_5_1_CODEX_MAX_LOW",
    1.25,
    10,
  ),
  "gpt-5-1-codex-max-medium": windsurfModel(
    "gpt-5-1-codex-max-medium",
    "GPT-5.1-Codex Max Medium",
    "MODEL_GPT_5_1_CODEX_MAX_MEDIUM",
    1.25,
    10,
  ),
  "gpt-5-1-codex-mini-low": windsurfModel(
    "gpt-5-1-codex-mini-low",
    "GPT-5.1-Codex-Mini Low",
    "MODEL_GPT_5_1_CODEX_MINI_LOW",
    0.25,
    2,
  ),
  "gpt-5-1-codex-mini": windsurfModel(
    "gpt-5-1-codex-mini",
    "GPT-5.1-Codex-Mini",
    "MODEL_PRIVATE_19",
    0.25,
    2,
  ),
  "gpt-5-1-codex-medium": windsurfModel(
    "gpt-5-1-codex-medium",
    "GPT-5.1-Codex Medium",
    "MODEL_PRIVATE_9",
    0.25,
    2,
  ),

  // ── GPT-5.2 ─────────────────────────────────────────────────────────────
  "gpt-5-2-none": windsurfModel(
    "gpt-5-2-none",
    "GPT-5.2 No Thinking",
    "MODEL_GPT_5_2_NONE",
    1.75,
    14,
  ),
  "gpt-5-2-none-fast": windsurfModel(
    "gpt-5-2-none-fast",
    "GPT-5.2 No Thinking Fast",
    "MODEL_GPT_5_2_NONE_PRIORITY",
    3.5,
    28,
  ),
  "gpt-5-2-low": windsurfModel(
    "gpt-5-2-low",
    "GPT-5.2 Low Thinking",
    "MODEL_GPT_5_2_LOW",
    1.75,
    14,
  ),
  "gpt-5-2-low-fast": windsurfModel(
    "gpt-5-2-low-fast",
    "GPT-5.2 Low Thinking Fast",
    "MODEL_GPT_5_2_LOW_PRIORITY",
    3.5,
    28,
  ),
  "gpt-5-2-medium": windsurfModel(
    "gpt-5-2-medium",
    "GPT-5.2 Medium Thinking",
    "MODEL_GPT_5_2_MEDIUM",
    1.75,
    14,
  ),
  "gpt-5-2-medium-fast": windsurfModel(
    "gpt-5-2-medium-fast",
    "GPT-5.2 Medium Thinking Fast",
    "MODEL_GPT_5_2_MEDIUM_PRIORITY",
    3.5,
    28,
  ),
  "gpt-5-2-high": windsurfModel(
    "gpt-5-2-high",
    "GPT-5.2 High Thinking",
    "MODEL_GPT_5_2_HIGH",
    1.75,
    14,
  ),
  "gpt-5-2-high-fast": windsurfModel(
    "gpt-5-2-high-fast",
    "GPT-5.2 High Thinking Fast",
    "MODEL_GPT_5_2_HIGH_PRIORITY",
    3.5,
    28,
  ),
  "gpt-5-2-xhigh": windsurfModel(
    "gpt-5-2-xhigh",
    "GPT-5.2 XHigh Thinking",
    "MODEL_GPT_5_2_XHIGH",
    1.75,
    14,
  ),
  "gpt-5-2-xhigh-fast": windsurfModel(
    "gpt-5-2-xhigh-fast",
    "GPT-5.2 XHigh Thinking Fast",
    "MODEL_GPT_5_2_XHIGH_PRIORITY",
    3.5,
    28,
  ),

  // ── GPT-5.2 Codex ───────────────────────────────────────────────────────
  "gpt-5-2-codex-low": windsurfModel(
    "gpt-5-2-codex-low",
    "GPT-5.2-Codex Low",
    "MODEL_GPT_5_2_CODEX_LOW",
    1.75,
    14,
  ),
  "gpt-5-2-codex-low-fast": windsurfModel(
    "gpt-5-2-codex-low-fast",
    "GPT-5.2-Codex Low Fast",
    "MODEL_GPT_5_2_CODEX_LOW_PRIORITY",
    3.5,
    28,
  ),
  "gpt-5-2-codex-medium": windsurfModel(
    "gpt-5-2-codex-medium",
    "GPT-5.2-Codex Medium",
    "MODEL_GPT_5_2_CODEX_MEDIUM",
    1.75,
    14,
  ),
  "gpt-5-2-codex-medium-fast": windsurfModel(
    "gpt-5-2-codex-medium-fast",
    "GPT-5.2-Codex Medium Fast",
    "MODEL_GPT_5_2_CODEX_MEDIUM_PRIORITY",
    3.5,
    28,
  ),
  "gpt-5-2-codex-high": windsurfModel(
    "gpt-5-2-codex-high",
    "GPT-5.2-Codex High",
    "MODEL_GPT_5_2_CODEX_HIGH",
    1.75,
    14,
  ),
  "gpt-5-2-codex-high-fast": windsurfModel(
    "gpt-5-2-codex-high-fast",
    "GPT-5.2-Codex High Fast",
    "MODEL_GPT_5_2_CODEX_HIGH_PRIORITY",
    3.5,
    28,
  ),
  "gpt-5-2-codex-xhigh": windsurfModel(
    "gpt-5-2-codex-xhigh",
    "GPT-5.2-Codex XHigh",
    "MODEL_GPT_5_2_CODEX_XHIGH",
    1.75,
    14,
  ),
  "gpt-5-2-codex-xhigh-fast": windsurfModel(
    "gpt-5-2-codex-xhigh-fast",
    "GPT-5.2-Codex XHigh Fast",
    "MODEL_GPT_5_2_CODEX_XHIGH_PRIORITY",
    3.5,
    28,
  ),

  // ── GPT-5.3 Codex ───────────────────────────────────────────────────────
  "gpt-5-3-codex-low": windsurfModel(
    "gpt-5-3-codex-low",
    "GPT-5.3-Codex Low",
    "gpt-5-3-codex-low",
    1.75,
    14,
  ),
  "gpt-5-3-codex-low-fast": windsurfModel(
    "gpt-5-3-codex-low-fast",
    "GPT-5.3-Codex Low Fast",
    "gpt-5-3-codex-low-priority",
    3.5,
    28,
  ),
  "gpt-5-3-codex-medium": windsurfModel(
    "gpt-5-3-codex-medium",
    "GPT-5.3-Codex Medium",
    "gpt-5-3-codex-medium",
    1.75,
    14,
  ),
  "gpt-5-3-codex-medium-fast": windsurfModel(
    "gpt-5-3-codex-medium-fast",
    "GPT-5.3-Codex Medium Fast",
    "gpt-5-3-codex-medium-priority",
    3.5,
    28,
  ),
  "gpt-5-3-codex-high": windsurfModel(
    "gpt-5-3-codex-high",
    "GPT-5.3-Codex High",
    "gpt-5-3-codex-high",
    1.75,
    14,
  ),
  "gpt-5-3-codex-high-fast": windsurfModel(
    "gpt-5-3-codex-high-fast",
    "GPT-5.3-Codex High Fast",
    "gpt-5-3-codex-high-priority",
    3.5,
    28,
  ),
  "gpt-5-3-codex-xhigh": windsurfModel(
    "gpt-5-3-codex-xhigh",
    "GPT-5.3-Codex X-High",
    "gpt-5-3-codex-xhigh",
    1.75,
    14,
  ),
  "gpt-5-3-codex-xhigh-fast": windsurfModel(
    "gpt-5-3-codex-xhigh-fast",
    "GPT-5.3-Codex XHigh Fast",
    "gpt-5-3-codex-xhigh-priority",
    3.5,
    28,
  ),
  "gpt-5-3-codex-spark-medium": windsurfModel(
    "gpt-5-3-codex-spark-medium",
    "GPT-5.3-Codex Spark Medium",
    "gpt-5-3-codex-spark-medium",
    1.75,
    14,
  ),

  // ── GPT-5.4 ─────────────────────────────────────────────────────────────
  "gpt-5-4-none": windsurfModel(
    "gpt-5-4-none",
    "GPT-5.4 No Thinking",
    "gpt-5-4-none",
    2.5,
    15,
  ),
  "gpt-5-4-none-fast": windsurfModel(
    "gpt-5-4-none-fast",
    "GPT-5.4 No Thinking Fast",
    "gpt-5-4-none-priority",
    5,
    30,
  ),
  "gpt-5-4-low": windsurfModel(
    "gpt-5-4-low",
    "GPT-5.4 Low Thinking",
    "gpt-5-4-low",
    2.5,
    15,
  ),
  "gpt-5-4-low-fast": windsurfModel(
    "gpt-5-4-low-fast",
    "GPT-5.4 Low Thinking Fast",
    "gpt-5-4-low-priority",
    5,
    30,
  ),
  "gpt-5-4-medium": windsurfModel(
    "gpt-5-4-medium",
    "GPT-5.4 Medium Thinking",
    "gpt-5-4-medium",
    2.5,
    15,
  ),
  "gpt-5-4-medium-fast": windsurfModel(
    "gpt-5-4-medium-fast",
    "GPT-5.4 Medium Thinking Fast",
    "gpt-5-4-medium-priority",
    5,
    30,
  ),
  "gpt-5-4-high": windsurfModel(
    "gpt-5-4-high",
    "GPT-5.4 High Thinking",
    "gpt-5-4-high",
    2.5,
    15,
  ),
  "gpt-5-4-high-fast": windsurfModel(
    "gpt-5-4-high-fast",
    "GPT-5.4 High Thinking Fast",
    "gpt-5-4-high-priority",
    5,
    30,
  ),
  "gpt-5-4-xhigh": windsurfModel(
    "gpt-5-4-xhigh",
    "GPT-5.4 XHigh Thinking",
    "gpt-5-4-xhigh",
    2.5,
    15,
  ),
  "gpt-5-4-xhigh-fast": windsurfModel(
    "gpt-5-4-xhigh-fast",
    "GPT-5.4 XHigh Thinking Fast",
    "gpt-5-4-xhigh-priority",
    5,
    30,
  ),

  // ── GPT-5.4 Mini ────────────────────────────────────────────────────────
  "gpt-5-4-mini-low": windsurfModel(
    "gpt-5-4-mini-low",
    "GPT-5.4 Mini Low Thinking",
    "gpt-5-4-mini-low",
    0.75,
    4.5,
  ),
  "gpt-5-4-mini-medium": windsurfModel(
    "gpt-5-4-mini-medium",
    "GPT-5.4 Mini Medium Thinking",
    "gpt-5-4-mini-medium",
    0.75,
    4.5,
  ),
  "gpt-5-4-mini-high": windsurfModel(
    "gpt-5-4-mini-high",
    "GPT-5.4 Mini High Thinking",
    "gpt-5-4-mini-high",
    0.75,
    4.5,
  ),
  "gpt-5-4-mini-xhigh": windsurfModel(
    "gpt-5-4-mini-xhigh",
    "GPT-5.4 Mini XHigh Thinking",
    "gpt-5-4-mini-xhigh",
    0.75,
    4.5,
  ),

  // ── GPT-5.5 ─────────────────────────────────────────────────────────────
  "gpt-5-5-none": windsurfModel(
    "gpt-5-5-none",
    "GPT-5.5 No Thinking",
    "gpt-5-5-none",
    2.5,
    15,
  ),
  "gpt-5-5-none-fast": windsurfModel(
    "gpt-5-5-none-fast",
    "GPT-5.5 No Thinking Fast",
    "gpt-5-5-none-priority",
    6.25,
    37.5,
  ),
  "gpt-5-5-low": windsurfModel(
    "gpt-5-5-low",
    "GPT-5.5 Low Thinking",
    "gpt-5-5-low",
    2.5,
    15,
  ),
  "gpt-5-5-low-fast": windsurfModel(
    "gpt-5-5-low-fast",
    "GPT-5.5 Low Thinking Fast",
    "gpt-5-5-low-priority",
    6.25,
    37.5,
  ),
  "gpt-5-5-medium": windsurfModel(
    "gpt-5-5-medium",
    "GPT-5.5 Medium Thinking",
    "gpt-5-5-medium",
    2.5,
    15,
  ),
  "gpt-5-5-medium-fast": windsurfModel(
    "gpt-5-5-medium-fast",
    "GPT-5.5 Medium Thinking Fast",
    "gpt-5-5-medium-priority",
    6.25,
    37.5,
  ),
  "gpt-5-5-high": windsurfModel(
    "gpt-5-5-high",
    "GPT-5.5 High Thinking",
    "gpt-5-5-high",
    2.5,
    15,
  ),
  "gpt-5-5-high-fast": windsurfModel(
    "gpt-5-5-high-fast",
    "GPT-5.5 High Thinking Fast",
    "gpt-5-5-high-priority",
    6.25,
    37.5,
  ),
  "gpt-5-5-xhigh": windsurfModel(
    "gpt-5-5-xhigh",
    "GPT-5.5 XHigh Thinking",
    "gpt-5-5-xhigh",
    2.5,
    15,
  ),
  "gpt-5-5-xhigh-fast": windsurfModel(
    "gpt-5-5-xhigh-fast",
    "GPT-5.5 XHigh Thinking Fast",
    "gpt-5-5-xhigh-priority",
    6.25,
    37.5,
  ),
  "gpt-5-5-review": windsurfModel(
    "gpt-5-5-review",
    "GPT 5.5 Review",
    "gpt-5-5-review",
    2.5,
    15,
  ),

  // ── GPT-OSS ─────────────────────────────────────────────────────────────
  "gpt-oss-120b": windsurfModel(
    "gpt-oss-120b",
    "GPT-OSS 120B Medium Thinking",
    "MODEL_GPT_OSS_120B",
    0.15,
    0.6,
  ),

  // ── Google ──────────────────────────────────────────────────────────────
  "gemini-2-5-pro": windsurfModel(
    "gemini-2-5-pro",
    "Gemini 2.5 Pro",
    "MODEL_GOOGLE_GEMINI_2_5_PRO",
    1.25,
    10,
  ),
  "gemini-3-0-flash-high": windsurfModel(
    "gemini-3-0-flash-high",
    "Gemini 3 Flash High",
    "MODEL_GOOGLE_GEMINI_3_0_FLASH_HIGH",
    0.5,
    3,
  ),
  "gemini-3-0-flash-low": windsurfModel(
    "gemini-3-0-flash-low",
    "Gemini 3 Flash Low",
    "MODEL_GOOGLE_GEMINI_3_0_FLASH_LOW",
    0.5,
    3,
  ),
  "gemini-3-0-flash-medium": windsurfModel(
    "gemini-3-0-flash-medium",
    "Gemini 3 Flash Medium",
    "MODEL_GOOGLE_GEMINI_3_0_FLASH_MEDIUM",
    0.5,
    3,
  ),
  "gemini-3-0-flash-minimal": windsurfModel(
    "gemini-3-0-flash-minimal",
    "Gemini 3 Flash Minimal",
    "MODEL_GOOGLE_GEMINI_3_0_FLASH_MINIMAL",
    0.5,
    3,
  ),
  "gemini-3-1-pro-high": windsurfModel(
    "gemini-3-1-pro-high",
    "Gemini 3.1 Pro High Thinking",
    "gemini-3-1-pro-high",
    2,
    12,
  ),
  "gemini-3-1-pro-low": windsurfModel(
    "gemini-3-1-pro-low",
    "Gemini 3.1 Pro Low Thinking",
    "gemini-3-1-pro-low",
    2,
    12,
  ),

  // ── xAI ─────────────────────────────────────────────────────────────────
  "xai-grok-3": windsurfModel(
    "xai-grok-3",
    "xAI Grok-3",
    "MODEL_XAI_GROK_3",
    3,
    15,
  ),
  "xai-grok-3-mini-thinking": windsurfModel(
    "xai-grok-3-mini-thinking",
    "xAI Grok-3 mini Thinking",
    "MODEL_XAI_GROK_3_MINI_REASONING",
    0.3,
    0.5,
    true,
  ),
  "grok-code-fast-1": windsurfModel(
    "grok-code-fast-1",
    "Grok Code Fast 1",
    "MODEL_PRIVATE_4",
    0.2,
    1.5,
  ),

  // ── DeepSeek ────────────────────────────────────────────────────────────
  "deepseek-v4": windsurfModel(
    "deepseek-v4",
    "DeepSeek V4",
    "deepseek-v4",
    1.74,
    3.48,
  ),

  // ── Kimi ────────────────────────────────────────────────────────────────
  "kimi-k2-5": windsurfModel("kimi-k2-5", "Kimi K2.5", "kimi-k2-5", 0.6, 3),
  "kimi-k2-6": windsurfModel("kimi-k2-6", "Kimi K2.6", "kimi-k2-6", 0.95, 4),

  // ── GLM ─────────────────────────────────────────────────────────────────
  "glm-5-1": windsurfModel("glm-5-1", "GLM-5.1", "glm-5-1", 1.4, 4.4),

  // ── MiniMax ─────────────────────────────────────────────────────────────
  "minimax-m2-5": windsurfModel("minimax-m2-5", "Minimax M2.5", "minimax-m2-5", 0.3, 1.2),

  // ── SWE ─────────────────────────────────────────────────────────────────
  "swe-1-5": windsurfModel("swe-1-5", "SWE-1.5 Fast", "MODEL_SWE_1_5", 0.3, 1.5),
  "swe-1-5-slow": windsurfModel("swe-1-5-slow", "SWE-1.5", "MODEL_SWE_1_5_SLOW", 0, 0),
  "swe-1-6": windsurfModel("swe-1-6", "SWE-1.6", "swe-1-6", 0, 0),
  "swe-1-6-fast": windsurfModel("swe-1-6-fast", "SWE-1.6 Fast", "swe-1-6-fast", 0.3, 1.5),
  "swe-check": windsurfModel("swe-check", "SWE-check", "swe-check", 0, 0),
}
